table 'Person Fact'
	lineageTag: 042b4ea7-046e-406d-9ab1-8f9a4c9168a2

	column ReportedIssue_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b22e929b-eb43-432f-9777-f5487944ce82
		summarizeBy: none
		sourceColumn: ReportedIssue_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ReportedIssuePerson_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b611b88e-5be1-4a41-acbb-e13909b2c2ec
		summarizeBy: none
		sourceColumn: ReportedIssuePerson_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Wallet_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f0901b9f-3761-4831-b6ad-6e983515a74a
		summarizeBy: none
		sourceColumn: Wallet_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Person Count' = 1
		formatString: 0
		lineageTag: c323b8f1-ed54-4c4c-bb3c-e02a271b7946
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Investigation
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 41818119-6703-4f0d-9887-28f296c1857a
		summarizeBy: none
		sourceColumn: Investigation

		annotation SummarizationSetBy = Automatic

	column 'Workflow Stage (Person)' = IF('Person Fact'[Investigation], "Investigation Stage", "Reporting Stage")
		lineageTag: 013d3b96-c584-442f-89ca-fb9a532ed38b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ReportedIssuePersonId
		dataType: string
		isHidden
		lineageTag: 3fc8862c-e684-400e-aee5-af02a56d5949
		summarizeBy: none
		sourceColumn: ReportedIssuePersonId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ReportedIssuePersonOptionType_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: acf55619-c631-468c-96d3-4ff2ac4c0390
		summarizeBy: none
		sourceColumn: ReportedIssuePersonOptionType_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Contact_key
		dataType: int64
		formatString: 0
		lineageTag: b1f390ba-48e2-4bab-9f5b-cdb915d37a99
		summarizeBy: none
		sourceColumn: Contact_key

		annotation SummarizationSetBy = User

	column 'Entered First Name'
		dataType: string
		lineageTag: 83623f1f-0716-4070-9ca3-f0aea9d75004
		summarizeBy: none
		sourceColumn: Entered First Name

		annotation SummarizationSetBy = Automatic

	column 'Entered Last Name'
		dataType: string
		lineageTag: 785702dd-ddd0-430c-ba89-3978c9c4bb31
		summarizeBy: none
		sourceColumn: Entered Last Name

		annotation SummarizationSetBy = Automatic

	column 'Entered Email'
		dataType: string
		lineageTag: fa41754f-8eb9-4f27-b6e5-ba16647326c0
		summarizeBy: none
		sourceColumn: Entered Email

		annotation SummarizationSetBy = Automatic

	column Name =
			
			VAR PersonOptionTypeCode = RELATED('Person Option Type'[PersonOptionTypeCode])
			RETURN
			    SWITCH(
			        TRUE(),
			        PersonOptionTypeCode = -1, BLANK(),
			        PersonOptionTypeCode IN { 2, 3 }, RELATED('Person Contact'[Contact Name]),
			        'Person Fact'[Entered First Name] & " " & 'Person Fact'[Entered Last Name]
			    )
		lineageTag: 0cec5b19-ad90-45ca-81d7-c8fcc4bfec95
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Email =
			
			VAR PersonOptionTypeCode = RELATED('Person Option Type'[PersonOptionTypeCode])
			RETURN
			    SWITCH(
			        TRUE(),
			        PersonOptionTypeCode = -1, BLANK(),
			        PersonOptionTypeCode IN { 2, 3 }, RELATED('Person Contact'[Email]),
			        'Person Fact'[Entered Email]
			    )
		lineageTag: 94a0bf11-dde2-4f43-a41b-63c77fa492b0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Person Fact-54090a2b-0786-481d-ad9e-863d39d1d27a' = m
		mode: import
		source =
				let
				    Source = Sql.Database("demo-workwalletbi.database.windows.net", "demo-workwalletbi"),
				    mart_ReportedIssuePersonFact = Source{[Schema="mart",Item="ReportedIssuePersonFact2"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(mart_ReportedIssuePersonFact,{"_created", "_edited"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"FirstName", "Entered First Name"}, {"LastName", "Entered Last Name"}, {"Email", "Entered Email"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

